apiVersion: v1
kind: Service
metadata:
  name: frontend-clusterip-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 30036